cors:
  originPatterns: http://localhost:8080,http://localhost:3000, https://www.erudio.com.br

file:
  uploadDir: ./uploads

email:
  subject: "Default Subject"
  message: "Default Message"

spring:
  application:
    name: spring-bootcamp

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_bootcamp?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: ${DB_USER}
    password: ${DB_PW}

  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    clean-disabled: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USER}
    password: ${GMAIL_PW}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2048
      max-file-size: 209715200
      max-request-size: 225485783

logging:
  level:
    root: INFO

spring-doc:
  paths-to-match: /api/**/v1/**
  swagger-ui:
    use-root-path: true